// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgepjipkydqrzuwksnve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZXBqaXBreWRxcnp1d2tzbnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDgxNTEsImV4cCI6MjA1ODk4NDE1MX0.2YSz-XYfKpObkC4sMuFdqyJ_8ZLQiXA81b28UEf5wP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);